```
SET B
```

In [1]:

#Q1  Write a program to count the number of vowels and consonants present in an input string.

def count_vowels_and_consonants(input_string):
    vowels = "AEIOUaeiou"
    consonants = "BCDFGHJKLMNPQRSTVWXYZbcdfghjklmnpqrstvwxyz"

    vowel_count = 0
    consonant_count = 0
    for char in input_string:
        if char in vowels:
            vowel_count += 1
        elif char in consonants:
            consonant_count += 1

    return vowel_count, consonant_count


str1="Hi Noob Nikhil"
vowel_count, consonant_count = count_vowels_and_consonants(str1)
print("Number of vowels:", vowel_count)
print("Number of consonants:", consonant_count)


Number of vowels: 5
Number of consonants: 7


In [17]:
#Q2 Write a program that accepts two matrices A and B as input and returns their product AB. Check if A & B are multipliable; if not, return error message

import numpy as np

def matrix_multiplication(A, B):
  m1=len(A)
  n1=len(A[0])
  m2=len(B)
  n2=len(B[0])

  if n1!=m2:
    print("Matrices cannot be multiplied")

  else:
    C=[]
    for i1 in range(0,m1):
      c=[]
      for i2 in range(0,n2):
        sum=0
        for j1 in range(0,m2):
          sum+=A[i1][j1]*B[j1][i2]
        c.append(sum)
      C.append(c)
    return C

def check_if_correct(A,B,C):
  A1=np.array(A)
  B1=np.array(B)
  C11=np.matmul(A1,B1)
  C1=np.array(C)
  if np.all(C11==C1):
    print("Works correctly")
  else:
    print("Incorrect")


A1=[[1,2,3],[4,5,6],[7,8,9]]

C1=matrix_multiplication(A1,A1)
print(C1)

# To check if it works correctly
check_if_correct(A1,A1,C1)
A3=[[1],[2],[3]]
C3=matrix_multiplication(A1,A3)
print(C3)
check_if_correct(A1,A3,C3)

[[30, 36, 42], [66, 81, 96], [102, 126, 150]]
Works correctly
[[14], [32], [50]]
Works correctly


In [12]:
#Q3 Write a program to find the number of common elements between two lists. The lists contain integers.



def check_common_elements(l1,l2):
  count=0
  com=[]
  for x in l1:
    if x in l2:
      if x not in com:
        count+=1
        com.append(x)
  return count
L1=list(range(0,10))
L2=list(range(5,10))

count=check_common_elements(L1,L2)
print(count)

5


In [50]:
#Q4  Write a program that accepts a matrix as input and returns its transpose.
import numpy as np

def matrix_transpose(M):
  m=len(M)
  n=len(M[0])
  for i in range(0,m):
    for j in range(0,n):
      if i<=j:
        temp=M[i][j]
        M[i][j]=M[j][i]
        M[j][i]=temp
  return M


def check_if_correct1(M,T):
  M1=np.array(M)
  print(M1)
  M2=M1.transpose()
  T1=np.array(T)
  if np.all(M2==T1):
    print("Works Correctly")

  else:
    print("Incorrect")


A1=[[1,2,3],[4,5,6],[7,8,9]]
print(np.array(A1))
A3=[[1,2,3],[4,5,6],[7,8,9]]
A2=matrix_transpose(A1)
#print(A2)
check_if_correct1(A3,A2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Works Correctly
