<a href="https://colab.research.google.com/github/Vector42-rev/learning_to_make_machine_learn/blob/lab_stuff/ML_LAB_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
A1. Please refer to the “Purchase Data” worksheet of Lab Session Data.xlsx. Please load the data
and segregate them into 2 matrices A & C (following the nomenclature of AX = C). Do the following
activities.
• What is the dimensionality of the vector space for this data?
• How many vectors exist in this vector space?
• What is the rank of Matrix A?
• Using Pseudo-Inverse find the cost of each product available for sale.
(Suggestion: If you use Python, you can use numpy.linalg.pinv() function to get a
pseudo-inverse.)
"""

In [27]:
import pandas as pd
import numpy as np

path="/content/drive/MyDrive/ML/lab3/Lab Session Data_1.csv"
df=pd.read_csv(path)
print(df)
df1=df[['Candies','Mangoes','Milk Packets']]
A1=df1.to_numpy()
#print(A1)
df2=df['Payment']
C1=df2.to_numpy()
C=np.array(C1).reshape(-1,1)
print(C)
A=np.array(A1)
print(A)
print("The rank of the matrix A is:- ")
rank=np.linalg.matrix_rank(A)
print(rank)

print("Dimensionality :-")

augmented_matrix = np.hstack([A, C])
rank_augmented = np.linalg.matrix_rank(augmented_matrix)
num_variables = A.shape[1]

if rank == rank_augmented:
    dimension_solution_space = num_variables - rank
    print(f"Dimension of the solution space: {dimension_solution_space}")
    if dimension_solution_space > 0:
        print("There are infinitely many solutions.")
    elif dimension_solution_space == 0:
        print("There is a unique solution.")
else:
    print("The system is inconsistent and has no solutions.")


Ai=np.linalg.pinv(A)
print("Cost of each item:- ")
X=np.dot(Ai,C)
print(X)


  Customer  Candies  Mangoes  Milk Packets  Payment
0      C_1       20        6             2      386
1      C_2       16        3             6      289
2      C_3       27        6             2      393
3      C_4       19        1             2      110
4      C_5       24        4             2      280
5      C_6       22        1             5      167
6      C_7       15        4             2      271
7      C_8       18        4             2      274
8      C_9       21        1             4      148
9     C_10       16        2             4      198
[[386]
 [289]
 [393]
 [110]
 [280]
 [167]
 [271]
 [274]
 [148]
 [198]]
[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
The rank of the matrix A is:- 
3
Dimensionality :-
Dimension of the solution space: 0
There is a unique solution.
Cost of each item:- 
[[ 1.]
 [55.]
 [18.]]


In [ ]:
#A2. Use the Pseudo-inverse to calculate the model vector X for predicting the cost of the products available with the vendor.

#Answer in previous cell

In [28]:
"""
A3. Mark all customers (in “Purchase Data” table) with payments above Rs. 200 as RICH and others
as POOR. Develop a classifier model to categorize customers into RICH or POOR class based on
purchase behavior
"""


def classifier_model():
  path="/content/drive/MyDrive/ML/lab3/Lab Session Data_1.csv"
  df=pd.read_csv(path)
  df['R/P'] =np.where(df['Payment']>200,'RICH','POOR')
  print(df)


classifier_model()


  Customer  Candies  Mangoes  Milk Packets  Payment   R/P
0      C_1       20        6             2      386  RICH
1      C_2       16        3             6      289  RICH
2      C_3       27        6             2      393  RICH
3      C_4       19        1             2      110  POOR
4      C_5       24        4             2      280  RICH
5      C_6       22        1             5      167  POOR
6      C_7       15        4             2      271  RICH
7      C_8       18        4             2      274  RICH
8      C_9       21        1             4      148  POOR
9     C_10       16        2             4      198  POOR


In [ ]:
"""
A4. Please refer to the data present in “IRCTC Stock Price” data sheet of the above excel file. Do the
following after loading the data to your programming platform.
• Calculate the mean and variance of the Price data present in column D.
(Suggestion: if you use Python, you may use statistics.mean() &
statistics.variance() methods).
• Select the price data for all Wednesdays and calculate the sample mean. Compare the mean
with the population mean and note your observations.
• Select the price data for the month of Apr and calculate the sample mean. Compare the
mean with the population mean and note your observations.
• From the Chg% (available in column I) find the probability of making a loss over the stock.
(Suggestion: use lambda function to find negative values)
• Calculate the probability of making a profit on Wednesday.
• Calculate the conditional probability of making profit, given that today is Wednesday.
• Make a scatter plot of Chg% data against the day of the week

"""